quarkus:
  http:
    port: 8080
    cors:
      ~: true
      origins: http://localhost:8080,http://localhost:4200
      headers: accept, authorization, content-type, x-requested-with
      methods: GET, POST, PUT, DELETE, OPTION
      exposed-headers: Content-Disposition,Set-Cookie
      access-control-allow-credentials: true
  naming:
    enable-jndi: true
  metrics:
    enable: true
    export:
      # Choose Prometheus as the metrics exporter
      prometheus:
        enabled: true
        path: /q/metrics
  smallrye-openapi:
    info-title: TODO
    info-version: 1.0.0
    info-description: API for the TODO
    info-terms-of-service: Your terms here
  swagger-ui:
    always-include: false
    title: Todo API
    footer: 2023 . com.example
    theme: original
  healthv:
    openapi:
      included: true

#
# Dev configuration
#
"%dev":
  custom:
    db:
      name: todo
      username: test
      password: test
      url: localhost
      port: 5432
    liquibase:
      migrate: true
  quarkus:
    hibernate-orm:
      database:
        default-catalog: ${custom.db.name}
        #generation: validate
    datasource:
      devservices:
        enabled: false
      db-kind: postgresql
      username: ${custom.db.username}
      password: ${custom.db.password}
      jdbc:
        ~: false
        url: jdbc:postgresql://${custom.db.url}:${custom.db.port}/${custom.db.name}
      reactive:
        url: postgresql://${custom.db.url}:${custom.db.port}/${custom.db.name}
        max-size: 10
    smallrye-openapi:
      info-title: Todo (development)
    liquibase:
      migrate-at-start: true
      change-log: db/changeLog.xml
      liquibase-schema-name: public
      default-schema-name: public
      database-change-log-lock-table-name: databasechangeloglock
      database-change-log-table-name: databasechangelog

#
# Dev configuration
#
"%prod":
  custom:
    db:
      name: todo-prod
      username: test
      password: test
      url: 10.88.0.3
      port: 5432
    liquibase:
      migrate: true
  quarkus:
    hibernate-orm:
      database:
        default-catalog: ${custom.db.name}
        #generation: validate
    datasource:
      devservices:
        enabled: false
      db-kind: postgresql
      username: ${custom.db.username}
      password: ${custom.db.password}
      jdbc:
        ~: false
        url: jdbc:postgresql://${custom.db.url}:${custom.db.port}/${custom.db.name}
      reactive:
        url: postgresql://${custom.db.url}:${custom.db.port}/${custom.db.name}
        max-size: 10
    smallrye-openapi:
      info-title: Todo (development)
    liquibase:
      migrate-at-start: true
      change-log: db/changeLog.xml
      liquibase-schema-name: public
      default-schema-name: public
      database-change-log-lock-table-name: databasechangeloglock
      database-change-log-table-name: databasechangelog

#
# Tests are executed with Testcontainers
#
"%test":
  custom:
    db:
      name: todo
      username: test
      password: test
    liquibase:
      migrate: true
  quarkus:
    hibernate-orm:
      database:
        default-catalog: ${custom.db.name}
        generation: validate
    datasource:
      devservices:
        enabled: true
      db-kind: postgresql
      username: ${custom.db.username}
      password: ${custom.db.password}
      jdbc:
        ~: false
        url: jdbc:tc:postgresql:latest:///${custom.db.name}
      reactive:
        url: jdbc:tc:postgresql:latest:///${custom.db.name}
    smallrye-openapi:
      info-title: Todo (DevTest)
    liquibase:
      migrate-at-start: true
      change-log: db/changeLog.xml
      liquibase-schema-name: public
      default-schema-name: public
      database-change-log-lock-table-name: databasechangeloglock
      database-change-log-table-name: databasechangelog
